create table if not exists public.claw_settle_logs (
  id bigint generated by default as identity primary key,
  session_id numeric(78, 0) not null,
  phase text not null,
  level text not null default 'info',
  message text,
  tx_hash text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists claw_settle_logs_session_id_created_at_idx
  on public.claw_settle_logs (session_id, created_at desc);
